<#!
.SYNOPSIS
  Create a POS Config & Setup package for LS Central SaaS.

.PARAMETER Path
  Path to a folder or file(s) to include in the package (e.g., JSON, REG, scripts). Defaults to POSConfig subfolder.

.PARAMETER OutputDir
  Output folder for the built package (.zip). Mandatory.

.PARAMETER Id
  Package Id. Defaults to 'pos-config'.

.PARAMETER Name
  Package display name. Defaults to 'POS Config & Setup'.

.PARAMETER Import
  If set, import the package to an Update Service server after building.

.PARAMETER Server
  Update Service server URL/hostname used when -Import is specified.

.PARAMETER Force
  Overwrite existing package on disk or on server.
#>
param(
  [string] $Path,
  [Parameter(Mandatory)] [string] $OutputDir,
  [string] $Id = 'pos-config',
  [string] $Name = 'POS Config & Setup',
  [string] $Version,
  [switch] $Import,
  [string] $Server,
  [switch] $Force
)
$ErrorActionPreference = 'stop'
try { Import-Module UpdateServiceServer -ErrorAction Stop } catch { }

if (-not $Path) { $Path = Join-Path $PSScriptRoot 'POSConfig\*' }
if (-not $Version) { $Version = (Get-Date).ToString('yyyy.MM.dd.HHmm') }

$pkg = @{
  Id = $Id
  Name = $Name
  Version = $Version
  InputPath = @(
    $Path,
    (Join-Path $PSScriptRoot '*')
  )
  OutputDir = $OutputDir
  Instance = $true
  Commands = @{ Install = 'Package.psm1:Install-Package'; Update = 'Package.psm1:Install-Package' }
  Parameters = @(
    @{ Key = 'StoreNumber'; Description = 'Store ID' }
    @{ Key = 'POSID'; Description = 'POS Terminal ID' }
    @{ Key = 'Company'; Description = 'Company name override (optional)' }
    @{ Key = 'POSUserName'; Description = 'POS user name (default POS)' }
    @{ Key = 'POSUserPassword'; Description = 'POS user password (autogenerated if empty)' }
    @{ Key = 'POSAdminUserName'; Description = 'Admin user name (default POSADMIN)' }
    @{ Key = 'POSAdminPassword'; Description = 'Admin user password (autogenerated if empty)' }
    @{ Key = 'POSPermissionSetId'; Description = 'Permission set for POS (default SUPER (DATA))' }
    @{ Key = 'POSPermissionSetAppName'; Description = 'App name for POS permission (default System Application)' }
    @{ Key = 'POSPermissionSetAppPublisher'; Description = 'App publisher for POS permission (default Microsoft)' }
    @{ Key = 'POSAdminPermissionSetId'; Description = 'Permission set for POSADMIN (default SUPER)' }
    @{ Key = 'CodeunitId'; Description = 'Codeunit Id to invoke (default 50101)' }
    @{ Key = 'MethodName'; Description = 'Method to invoke (default SetupPOSEnvironment)' }
  )
  Dependencies = @(
    @{ Id = 'bc-web-client'; VersionQuery = '' }
  )
}
$created = New-UssPackage @pkg -Force:$Force
if ($Import) { $created | Import-UssPackage -Server $Server -Force:$Force }
$created
